### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Andy-Donegan** [choppraNY/ExilePHPAdminTools#2]

**Comment by ATDChoppra** [comment]
I am only releasing it to those who pay for it.  It is a private / closed release.

**Comment by Andy-Donegan** [comment]
Ok good so there is a release, it is a huge step forward than where I was before I came here.
Can we discuss the price/cost. on here ? personal email ? or is there a site listing the project ?

Cheers and hope to speak soon.

**Comment by ATDChoppra** [comment]
message me on skype on exile forums directly.  Username is Choppra
