### ISSUE TITLE
(Request) Hived database

### ISSUE THREAD

**Issue by Newfoundland-Republic** [choppraNY/ExilePHPAdminTools#4]
Hi Choppra - great work! I *used to* (a looooong time ago) used to program in PHP and SQL and I am very, very rusty!

We have a couple of databases with a common hive database to share the play accounts, poptabs, families, etc., with the specific servers having their own databases. All the databases are on the same server.
I have:
1. exile_hive = shared base player  database
2. exile1 = database with map-specific information (e.g., territories) for server #1 
3. exile2 = database with map-specific information for server #2 

I have been trying to set up the queries using the three-party syntax (e.g., [DB01].[dbo].[myTable]) but no luck. Like I said, it has been a very long time!

Is this something that you can look into?

Thanks!

**Comment by Choppra** [comment]
sorry mate, this isn't something I plan on supporting.  This would have to be something you figure out on your own.  Essentially all the queries need to adjusted.

**Comment by Newfoundland-Republic** [comment]
Hi Choppra - You can close this one (unless you get some overwhelming desire to add it as a feature enhancement :-)) I did get it working but we decided to unhive our databases - it was causing more issues than any benefits. Thanks for getting back to me! (...and for giving me the opportunity to remember explicit joins :-))
