### ISSUE TITLE
Exile Extdb3

### ISSUE THREAD

**Issue by Falcon911** [choppraNY/ExilePHPAdminTools#5]
Can this be used for Exile 1.04 with exile extdb3

**Comment by Choppra** [comment]
Not sure but I don't see why not.  The exile.ini entries probably need to be adjusted.

**Comment by Falcon911** [comment]
Yeah I'm finding out that the Tables are not being updated any longer. Look like the database ID was changed on ya.

**Comment by Choppra** [comment]
feel free to request a fork to update it.
