### ISSUE TITLE
searchlogs.php

### ISSUE THREAD

**Issue by fruityrooty** [choppraNY/ExilePHPAdminTools#7]
Hi, i'm having an issue with 'searchlogs.php' I have the following error and i'm unsure of how to resolve it.

`SQLSTATE[21000]: Cardinality violation: 1241 Operand should contain 1 column(s)
Warning: Invalid argument supplied for foreach() in /usr/www/root/hap/searchlogs.php on line 65`

line 65 is the following: `foreach ($entries as $entry) {` 

Greats tools btw! 👍

**Comment by fruityrooty** [comment]
Fixed, do you have any plans to build in RCON?

**Comment by Choppra** [comment]
nope, unless i get back into ARMA
